name: d20
version: 0.0.1
authors:
- Igor Borges <igor@borges.me>
description: >
  D20 is a Dart library for RPG dice rolling. Supports standard notation (like "2d12", "d20+5" and "4d6*5").
homepage: https://github.com/Igor1201/d20

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  math_expressions: ^1.0.0

dev_dependencies:
  test: ^1.0.0
